Namespace(batchSize=64, beta1=0.5, cuda=True, dataroot='/disk/scratch/s1832582//datasets//paintings', dataset='folder', imageSize=64, lr=0.0002, manualSeed=None, ndf=64, netD='/home/s1832582/paintings_dcgan/netD_epoch_6.pth', netG='/home/s1832582/paintings_dcgan/netG_epoch_6.pth', ngf=64, ngpu=4, niter=25, nz=100, outf='/home/s1832582/paintings_dcgan', workers=2)
Random Seed:  2023
Traceback (most recent call last):
  File "dcgan.py", line 161, in <module>
    netG = Generator(ngpu).to(device)
  File "/home/s1832582/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 381, in to
    return self._apply(convert)
  File "/home/s1832582/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/s1832582/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 187, in _apply
    module._apply(fn)
  File "/home/s1832582/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 193, in _apply
    param.data = fn(param.data)
  File "/home/s1832582/miniconda3/envs/mlp/lib/python3.7/site-packages/torch/nn/modules/module.py", line 379, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
RuntimeError: CUDA error: initialization error
